### ISSUE TITLE
better use of whitespace - stan logo only

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan-dev.github.io#93]
critical landing page real estate is taken up by the logo (which bounces down to land in the middle of the loops which represent the ideal HMC trajectory) - can we simplify this to just the logo and allow more content to be visible?

**Comment by mitzimorris** [comment]
assigned to Imad - feel free to reassign

**Comment by mitzimorris** [comment]
fixed on branch https://github.com/stan-dev/stan-dev.github.io/tree/simplify-logo

@imadmali - requesting your review and help here - confused by what happens when I try to open a PR via GitHub web interface - it wants to merge back into mmistakes/so-simple-theme repo - I just want to merge into master branch of this repo - stan-dev/stan-dev.github.io

**Comment by imadmali** [comment]
@mitzimorris that happened to me too. idk why the default when submitting a PR is to merge into mmistakes/so-simple. 

I agree, the logo does take up quite a bit of space on each page of the site. However, we might wanna table the fix until we make some headway with the redesign since that might involve a different theme (and logo placement). (I wouldn't want anyone to put in effort only to have it all redone.)

**Comment by mitzimorris** [comment]
>  idk why the default when submitting a PR is to merge into mmistakes/so-simple.

me neither.  removed mmistakes/so-simple website from description on main github page.

> we might wanna table the fix 

agreed.  tabled.

**Comment by mitzimorris** [comment]
leaving this to the pros - closing
